name: mobile
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  call_log: ^6.0.1
  flutter:
    sdk: flutter
  http: ^1.6.0
  intl: ^0.20.2
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.7.0
  device_info_plus: ^10.1.2
  fl_chart: ^1.1.1
  workmanager: ^0.9.0
  package_info_plus: ^9.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/Splash_Screen/
    - assets/app_icon/
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon/DealVoice Logo.png"
